stages:
  - build

variables:
  XKALI_IMAGE_BASE_TAG: "20240811"

  # RDP port
  XRDP_PORT: 13389

  # VNC ports
  XVNC_DISPLAY: 8
  XVNC_PORT: 5908

  # SSH port
  XSSH_PORT: 20022

  # Container desktop environment
  # Options: "xfce" "mate" "kde" "e17" "gnome" "i3" "i3-gaps" "live" "lxde"
  XDESKTOP_ENVIRONMENT: "xfce"

  # Remote access method for desktop
  # Options: "vnc" "rdp" "x2go"
  # Once rdp is up, it may take a moment to load
  # Note: Only xfce works with rdp right now
  XREMOTE_ACCESS: "rdp"

  # Kali packages
  # Options: "arm" "core" "default" "everything" "firmware" "headless" "labs" "large" "nethunter"
  XKALI_PKG: "core"

  # Username for container user
  USERNAME: "xuser"

  # Password for container user
  PASSWORD: "password123"

build:
  stage: build
  tags:
    - image-builder
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "BRANCH=$(echo test)" >> .env
    - export $(cat .env | xargs)
    # Provenance false is used to circumvent buildx push issue on gitlab container registry
    # more at: https://gitlab.com/gitlab-org/gitlab/-/issues/388865
    # However, this is apparently fixed in the new "Next generation" container registry which
    # is available in gitlab 17.3.
    - |
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker buildx create --use
      echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
      docker buildx build \
        --provenance false \
        --platform linux/amd64,linux/arm64 \
        --push \
        -t $CI_REGISTRY_IMAGE:$BRANCH \
        --cache-from type=registry,ref=$CI_REGISTRY_IMAGE:$BRANCH \
        --cache-to type=inline \
        --build-arg DESKTOP_ENVIRONMENT=$XDESKTOP_ENVIRONMENT \
        --build-arg REMOTE_ACCESS=$XREMOTE_ACCESS \
        --build-arg KALI_PACKAGE=$XKALI_PKG \
        --build-arg RDP_PORT=$XRDP_PORT \
        --build-arg SSH_PORT=$XSSH_PORT \
        --build-arg UNAME=$USERNAME \
        --build-arg UPASS=$PASSWORD \
        .
