name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # RDP port
  XRDP_PORT: 13389

  # VNC ports
  XVNC_DISPLAY: 8
  XVNC_PORT: 5908

  # SSH port
  XSSH_PORT: 20022

  # Container desktop environment
  # Options: "xfce" "mate" "kde" "e17" "gnome" "i3" "i3-gaps" "live" "lxde"
  XDESKTOP_ENVIRONMENT: "xfce"

  # Remote access metohod for desktop
  # Options: "vnc" "rdp" "x2go"
  # Once rdp is up, it may take a moment to load
  # Note: Only xfce works with rdp right now
  XREMOTE_ACCESS: "rdp"

  # Kali packages
  # Options: "arm" "core" "default" "everything" "firmware" "headless" "labs" "large" "nethunter"
  XKALI_PKG: "core"

  # Name for local custom Docker image
  DOCKERIMG: "tfalesni/kali-linux"

  # Username for container user
  USERNAME: "user"

  # Password for container user
  PASSWORD: "password123"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERIMG }}:${{ env.BRANCH }}
          cache-from: type=registry,ref=${{ env.DOCKERIMG }}:${{ env.BRANCH }}
          cache-to: type=inline
          build-args: |
            DESKTOP_ENVIRONMENT=${{ env.XDESKTOP_ENVIRONMENT }}
            REMOTE_ACCESS=${{ env.XREMOTE_ACCESS }}
            KALI_PACKAGE=${{ env.XKALI_PKG }}
            RDP_PORT=${{ env.XRDP_PORT }}
            UNAME=${{ env.USERNAME }}
            UPASS=${{ env.PASSWORD }}
